### ISSUE TITLE
Could not load type 'Unity.UnityContainerExtensions' from assembly 'Unity.Container, Version=5.9.2.0,....

### ISSUE THREAD

**Issue by MatzeG** [unitycontainer/configuration#13]
Hello 

I get an exception when configuring an extension from the config. Any ideas ??

var section = (UnityConfigurationSection)configuration.GetSection("unity");
section.Configure(container);

Exception:
System.TypeLoadException
Could not load type 'Unity.UnityContainerExtensions' from assembly 'Unity.Container, Version=5.9.2.0, Culture=neutral, PublicKeyToken=489b6accfaf20ef0'.
   at Microsoft.Practices.Unity.Configuration.ContainerExtensionElement.ConfigureContainer(IUnityContainer container)
   at Microsoft.Practices.Unity.Configuration.ContainerElement.ConfigureContainer(IUnityContainer container)
   at Microsoft.Practices.Unity.Configuration.UnityConfigurationSection.Configure(IUnityContainer container, String configuredContainerName)

**Comment by ENikS** [comment]
It has been renamed to [ExtensionExtensions](https://github.com/unitycontainer/container/blob/master/src/Extensions/ExtensionExtensions.cs) due to [this conflict](https://github.com/unitycontainer/abstractions/issues/95).

**Comment by MatzeG** [comment]
Hi 
but the code is inside Unity.Configuration - are you sure that the Versions match? I think Unity.Configuration must be compiled against Version > 5.9.2.0
