### ISSUE TITLE
It doesn't support .netcore 2.0?

### ISSUE THREAD

**Issue by 273299007** [unitycontainer/configuration#19]
it support .netcore2.0 in the guget below:
[https://www.nuget.org/packages/Unity.Configuration/](https://www.nuget.org/packages/Unity.Configuration/)

I did  a testing for .netcore 2.0 console application and found that  it  did not work. below is the details:

1.app.config:
`<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <configSections>
    <section name="unity" type="Microsoft.Practices.Unity.Configuration.UnityConfigurationSection,Unity.Configuration"/>
  </configSections>
  <unity xmlns="http://schemas.microsoft.com/practices/2010/unity">
    <alias alias="Ilogging" type="Will.Framework.Abstract.Logging.Ilogging, Will.Framework.Abstract" />
    <container>
      <register type="Ilogging" mapTo="Will.Logging.Win.ClsILogging, Will.Logging.Win" />
    </container>
  </unity>
</configuration>`

2. below is the function in class "Program"
<pre>
  private static void LoadDllTest()
        {
            using (var container = new UnityContainer())
            {
                var section = (UnityConfigurationSection)ConfigurationManager.GetSection("unity");
                section.Configure(container);
                var LoggingWeb = container.Resolve<Ilogging>();        
            }
        }
</pre>

3.Below is the exception from line of " section.Configure(container);":
<pre>
   at Microsoft.Practices.Unity.Configuration.ConfigurationHelpers.TypeResolverImpl.ResolveType(String typeNameOrAlias, Boolean throwIfResolveFails) in C:\projects\configuration\src\ConfigurationHelpers\TypeResolverImpl.cs:line 103
   at Microsoft.Practices.Unity.Configuration.RegisterElement.ConfigureContainer(IUnityContainer container)
   at Microsoft.Practices.Unity.Configuration.ContainerElement.ConfigureContainer(IUnityContainer container) in C:\projects\configuration\src\Elements\ContainerElement.cs:line 101
   at Microsoft.Practices.Unity.Configuration.UnityConfigurationSection.Configure(IUnityContainer container, String configuredContainerName) in C:\projects\configuration\src\Section\UnityConfigurationSection.cs:line 141
</pre>

4.If I added the reference of "Will.Logging.Win"  the function LoadDllTest will work.  But  for this situation, the unity container doesn't make any sense yet.  and I can just create the instance directly.

Any suggestion is appreciated!

Thanks

**Comment by ENikS** [comment]
At present Configuration is only supported on Full .NET framework
